- template:
    src: ./templates/gunicorn.socket.j2
    dest: /etc/systemd/system/gunicorn.socket
    owner: root
    mode: 0644

- template:
    src: ./templates/gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
    owner: root
    mode: 0644

- name: django | post | enable gunicorn socket
  service:
    name: gunicorn.socket
    enabled: true

- name: django | post | enable gunicorn socket
  service:
    name: gunicorn
    enabled: true