- template:
    src: ./templates/gunicorn.socket.j2
    dest: '/etc/systemd/system/{{ project_settings.project_name }}-gunicorn.socket'
    owner: root
    mode: 0644

- template:
    src: ./templates/gunicorn.service.j2
    dest: '/etc/systemd/system/{{ project_settings.project_name }}-gunicorn.service'
    owner: root
    mode: 0644

- name: django | post | enable gunicorn socket
  service:
    name: '{{ project_settings.project_name }}-gunicorn.socket'
    enabled: true

- name: django | post | enable gunicorn service
  service:
    name: '{{ project_settings.project_name }}-gunicorn.service'
    enabled: true