- name: django | pre | clean if needed
  file:
    state: absent
    path: "{{ project_settings.project_dir }}"
  when: clean_install

- name: django | pre | create database
  become_user: postgres
  postgresql_db:
    name: "{{ postgres_settings.django_database_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0

- name: django | pre | create database user
  become_user: postgres
  postgresql_user:
    db: "{{ postgres_settings.django_database_name }}"
    name: "{{ postgres_settings.django_database_user }}"
    password: "{{ postgres_settings.django_database_user_password }}"
    priv: "ALL"
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: django | pre | adjust db setttings
  become_user: postgres
  postgresql_query:
    db: "{{ postgres_settings.django_database_name }}"
    query: ALTER ROLE "{{ postgres_settings.django_database_user }}" SET timezone TO 'UTC';

- name: django | pre | create virtualenv
  command:
    cmd: python3 -m venv "{{ project_settings.venv_path }}"
  when: clean_install

- name: django | main | virtualenv with deps
  pip:
    name:
      - django
      - gunicorn
      - psycopg2-binary
    virtualenv: "{{ project_settings.venv_path }}"

- name: django | post | project init
  include_tasks: project.yml

- name: django | post | gunicorn configuration
  include_tasks: gunicorn.yml

- name: django | post | nginx configuration
  include_tasks: nginx.yml