- name: django | pre | create database
  become_user: postgres
  postgresql_db:
    name: "{{ postgres_settings.django_database_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0

- name: django | pre | create database user
  become_user: postgres
  postgresql_user:
    db: "{{ postgres_settings.django_database_name }}"
    name: "{{ postgres_settings.django_database_user }}"
    password: "{{ postgres_settings.django_database_user_password }}"
    priv: "ALL"
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: django | pre | adjust db setttings
  become_user: postgres
  postgresql_query:
    db: "{{ postgres_settings.django_database_name }}"
    query: ALTER ROLE "{{ postgres_settings.django_database_user }}" SET timezone TO 'UTC';

- name: django | pre | create virtualenv
  command:
    cmd: python3 -m venv "{{ project_settings.venv_path }}"

- name: django | main | virtualenv with deps
  pip:
    name:
      - django
      - gunicorn
      - psycopg2-binary
    virtualenv: "{{ project_settings.venv_path }}"

- name: django | main | create project
  command:
    cmd: "{{ project_settings.venv_path }}/bin/django-admin.py startproject {{ project_settings.project_name }} {{ project_settings.project_dir }}"

- template:
    src: ./templates/settings.j2
    dest: "{{ project_settings.project_dir}}/{{ project_settings.project_name }}/settings.py"
    owner: root
    mode: 0644

- name: django | main | make migrations
  command:
    cmd: "{{ project_settings.venv_path }}/bin/python {{ project_settings.project_dir }}/manage.py makemigrations"

- name: django | main | make migrate
  command:
    cmd: "{{ project_settings.venv_path }}/bin/python {{ project_settings.project_dir }}/manage.py migrate"

- name: django | main | collect statics
  command:
    cmd: "{{ project_settings.venv_path }}/bin/python {{ project_settings.project_dir }}/manage.py collectstatic"

# gunicorn part
# nginx part
