- name: django | pre | create database
  become_user: postgres
  postgresql_db:
    name: "{{ django_database_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0

- name: django | pre | create database user
  become_user: postgres
  postgresql_user:
    db: "{{ django_database_name }}"
    name: "{{ django_database_user }}"
    password: "{{ django_database_user_password }}"
    priv: "ALL"
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: django | pre | adjust db setttings
  become_user: postgres
  postgresql_query:
    db: "{{ django_database_name }}"
    query: ALTER ROLE "{{ django_database_user }}" SET timezone TO 'UTC';