- template:
    src: ./templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ project_settings.project_name }}
    owner: root
    mode: 0644

- file:
    src: /etc/nginx/sites-available/{{ project_settings.project_name }}
    dest: /etc/nginx/sites-enabled/{{ project_settings.project_name }}
    owner: root
    group: www-data
    state: link

- name: django | post | reload gunicorn socket
  service:
    name: '{{ project_settings.project_name }}-gunicorn.socket'
    state: restarted
    daemon_reload: yes

- name: django | post | reload gunicorn service
  service:
    name: '{{ project_settings.project_name }}-gunicorn.service'
    state: restarted
    daemon_reload: yes

- name: django | post | reload nginx at the end
  service:
    name: nginx
    state: restarted
    daemon_reload: yes