- name: docker | pre | Uninstall existing 
  apt: name={{ docker_uninstall_packages }} state=absent

- name: docker | pre | Install needed 
  apt: name={{ docker_required_packages }} update_cache=yes state=latest

- name: docker | pre | Add docker key for repo
  command:
    cmd: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null    

- name: docker | pre | Add docker repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: docker | main | Install docker
  apt: name={{ docker_main_packages }} update_cache=yes state=latest

- name: docker | post | Create docker group
  group:
    name: docker
    state: present

- name: docker | post | Add user {{ admin_user }} to docker group
  user:
    name: "{{ admin_user }}"
    groups: docker
    append: yes

- name: docker | post | Make sure service docker is enabled
  service:
    name: docker
    state: started
    enabled: true

- name: docker | post | Make sure service containerd is enabled
  service:
    name: containerd
    state: started
    enabled: true