- name: nginx | pre | Uninstall existing server
  apt:
    name: nginx
    state: absent

- name: nginx | main | Install web server
  apt:
    name: nginx
    state: present

- name: nginx | post | Make sure service is enabled
  service:
    name: nginx
    state: started
    enabled: true

- name: nginx | post | Initiate default site
  copy:
    src: ../files/index.html
    dest: /var/www/html/index.html
    owner: root
    mode: 0644
  when: create_default_site
  
- name: nginx | post | Validate site is up
  command: 
    cmd: curl localhost
  register: nginx_is_ip

- debug: 
    var: nginx_is_ip.stdout