- name: postgresql | pre | Uninstall existing server
  apt:
    name: postgresql
    state: absent

- name: postgresql | pre | Install needed 
  apt: name={{ postgres_required_packages }} update_cache=yes state=latest

- name: postgresql | main | Ensure the PostgreSQL service is running
  service:
    name: postgresql
    enabled: true