docker_uninstall_packages:
  - docker
  - docker-engine
  - docker.io
  - containerd
  - runc

docker_required_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

docker_main_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

admin_user: alexey